"""
Constants and configuration for Hangman Game.
"""
# Colors
BACKGROUND = (25, 35, 55)
ACCENT = (255, 215, 0)
TEXT_COLOR = (240, 240, 250)
BUTTON_COLOR = (70, 130, 180)
BUTTON_HOVER = (100, 160, 210)
RED = (220, 60, 60)
GREEN = (70, 180, 70)
LIGHT_BLUE = (100, 180, 255)

# Game words
WORDS = [
    "PYTHON", "PROGRAMMING", "DEVELOPMENT", "FRAMEWORK", "ALGORITHM",
    "APPLICATION", "OPERATING", "SYSTEM", "DATABASE", "NETWORK",
    "SECURITY", "INFORMATION", "COMPUTER", "PROGRAM", "CODE",
    "DESIGN", "ENGINEERING", "SCIENCE", "TECHNOLOGY", "INNOVATION",
    "CREATIVITY", "SOLUTION", "PROCESS", "ANALYSIS"
]

# Game settings
MAX_MISTAKES = 7
MESSAGE_DISPLAY_TIME = 60